### ISSUE TITLE
Unable to make

### ISSUE THREAD

**Issue by fossolution** [wickett/word-cloud-generator#5]
I have followed the instruction from README.md file and when I `make` I get the following error:
$ make
Cleaning up previous builds
Restoring dependencies...
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:	Current Directory: /Users/student/Desktop/DevOpsFoundation/word-cloud-generator
godep: [WARNING]:	$GOPATH: /Users/student/go
can't load package: package _/Users/student/Desktop/DevOpsFoundation/word-cloud-generator: cannot find package "_/Users/student/Desktop/DevOpsFoundation/word-cloud-generator" in any of:
	/usr/local/Cellar/go/1.11.5/libexec/src/_/Users/student/Desktop/DevOpsFoundation/word-cloud-generator (from $GOROOT)
	/Users/student/go/src/_/Users/student/Desktop/DevOpsFoundation/word-cloud-generator (from $GOPATH)
can't load package: package _/Users/student/Desktop/DevOpsFoundation/word-cloud-generator/wordyapi: cannot find package "_/Users/student/Desktop/DevOpsFoundation/word-cloud-generator/wordyapi" in any of:
	/usr/local/Cellar/go/1.11.5/libexec/src/_/Users/student/Desktop/DevOpsFoundation/word-cloud-generator/wordyapi (from $GOROOT)
	/Users/student/go/src/_/Users/student/Desktop/DevOpsFoundation/word-cloud-generator/wordyapi (from $GOPATH)
make: *** [test] Error 1

**Comment by adaptiman** [comment]
Same error.

**Comment by luis-carlos** [comment]
Same here. Installing on a Ubuntu 19.04 Docker image and Golang version go version go1.12.7 linux/amd64

**Comment by luis-carlos** [comment]
@adaptiman There seems to be a couple of double-quotes missing. 

Try Set $PATH export PATH="$PATH:$(go env GOPATH)/bin" for step 3, instead. Worked for me.

**Comment by wickett** [comment]
This looks like it should be working now, please reopen if it is still a problem
